# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'book_pane.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(771, 203)
        Form.setMinimumSize(QtCore.QSize(449, 203))
        Form.setStyleSheet("background-color: rgb(175, 175, 175);")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.radioButton = QtWidgets.QRadioButton(Form)
        self.radioButton.setObjectName("radioButton")
        self.buttonGroup = QtWidgets.QButtonGroup(Form)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioButton)
        self.gridLayout.addWidget(self.radioButton, 1, 0, 1, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(Form)
        self.radioButton_2.setObjectName("radioButton_2")
        self.buttonGroup.addButton(self.radioButton_2)
        self.gridLayout.addWidget(self.radioButton_2, 1, 1, 1, 1)
        self.radioButton_3 = QtWidgets.QRadioButton(Form)
        self.radioButton_3.setObjectName("radioButton_3")
        self.buttonGroup.addButton(self.radioButton_3)
        self.gridLayout.addWidget(self.radioButton_3, 1, 2, 1, 1)
        self.radioButton_4 = QtWidgets.QRadioButton(Form)
        self.radioButton_4.setObjectName("radioButton_4")
        self.buttonGroup.addButton(self.radioButton_4)
        self.gridLayout.addWidget(self.radioButton_4, 1, 3, 1, 1)
        self.radioButton_9 = QtWidgets.QRadioButton(Form)
        self.radioButton_9.setObjectName("radioButton_9")
        self.buttonGroup.addButton(self.radioButton_9)
        self.gridLayout.addWidget(self.radioButton_9, 1, 4, 1, 1)
        self.radioButton_5 = QtWidgets.QRadioButton(Form)
        self.radioButton_5.setObjectName("radioButton_5")
        self.buttonGroup.addButton(self.radioButton_5)
        self.gridLayout.addWidget(self.radioButton_5, 2, 0, 1, 1)
        self.radioButton_7 = QtWidgets.QRadioButton(Form)
        self.radioButton_7.setObjectName("radioButton_7")
        self.buttonGroup.addButton(self.radioButton_7)
        self.gridLayout.addWidget(self.radioButton_7, 2, 1, 1, 1)
        self.radioButton_6 = QtWidgets.QRadioButton(Form)
        self.radioButton_6.setObjectName("radioButton_6")
        self.buttonGroup.addButton(self.radioButton_6)
        self.gridLayout.addWidget(self.radioButton_6, 2, 2, 1, 1)
        self.radioButton_8 = QtWidgets.QRadioButton(Form)
        self.radioButton_8.setChecked(True)
        self.radioButton_8.setObjectName("radioButton_8")
        self.buttonGroup.addButton(self.radioButton_8)
        self.gridLayout.addWidget(self.radioButton_8, 2, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.phone_num_le = QtWidgets.QLineEdit(Form)
        self.phone_num_le.setMinimumSize(QtCore.QSize(0, 50))
        self.phone_num_le.setObjectName("phone_num_le")
        self.gridLayout.addWidget(self.phone_num_le, 4, 0, 1, 5)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 5, 4, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 5, 3, 1, 1)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(1, 2)
        self.gridLayout.setRowStretch(2, 2)
        self.gridLayout.setRowStretch(3, 1)
        self.gridLayout.setRowStretch(4, 1)
        self.gridLayout.setRowStretch(5, 1)

        self.retranslateUi(Form)
        self.pushButton.clicked.connect(Form.confirm)
        self.pushButton_2.clicked.connect(Form.cancel_query)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "座位席别"))
        self.radioButton.setText(_translate("Form", "无座"))
        self.radioButton.setProperty("val", _translate("Form", "WZ"))
        self.radioButton_2.setText(_translate("Form", "一等座"))
        self.radioButton_2.setProperty("val", _translate("Form", "M"))
        self.radioButton_3.setText(_translate("Form", "二等座"))
        self.radioButton_3.setProperty("val", _translate("Form", "O"))
        self.radioButton_4.setText(_translate("Form", "动卧"))
        self.radioButton_4.setProperty("val", _translate("Form", "M"))
        self.radioButton_9.setText(_translate("Form", "硬卧"))
        self.radioButton_9.setProperty("val", _translate("Form", "3"))
        self.radioButton_5.setText(_translate("Form", "软卧"))
        self.radioButton_5.setProperty("val", _translate("Form", "4"))
        self.radioButton_7.setText(_translate("Form", "高级软卧"))
        self.radioButton_7.setProperty("val", _translate("Form", "6"))
        self.radioButton_6.setText(_translate("Form", "商务座"))
        self.radioButton_6.setProperty("val", _translate("Form", "9"))
        self.radioButton_8.setText(_translate("Form", "硬座"))
        self.radioButton_8.setProperty("val", _translate("Form", "1"))
        self.label_2.setText(_translate("Form", "请输入你的手机号码"))
        self.pushButton.setText(_translate("Form", "确认"))
        self.pushButton_2.setText(_translate("Form", "取消"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

