# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'query_pane.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(775, 521)
        Form.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.query_pane_top = QtWidgets.QWidget(Form)
        self.query_pane_top.setStyleSheet("")
        self.query_pane_top.setObjectName("query_pane_top")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.query_pane_top)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.to_station_cb = QtWidgets.QComboBox(self.query_pane_top)
        self.to_station_cb.setEditable(True)
        self.to_station_cb.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.to_station_cb.setObjectName("to_station_cb")
        self.to_station_cb.addItem("")
        self.gridLayout_2.addWidget(self.to_station_cb, 0, 3, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.query_pane_top)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.pushButton = QtWidgets.QPushButton(self.query_pane_top)
        self.pushButton.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 0, 5, 2, 1)
        self.label_3 = QtWidgets.QLabel(self.query_pane_top)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.normal_cb = QtWidgets.QRadioButton(self.query_pane_top)
        self.normal_cb.setChecked(True)
        self.normal_cb.setObjectName("normal_cb")
        self.buttonGroup = QtWidgets.QButtonGroup(Form)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.normal_cb)
        self.gridLayout_2.addWidget(self.normal_cb, 1, 3, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.query_pane_top)
        self.pushButton_2.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_2.setMaximumSize(QtCore.QSize(8, 80))
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 0, 6, 2, 1)
        self.stu_cb = QtWidgets.QRadioButton(self.query_pane_top)
        self.stu_cb.setObjectName("stu_cb")
        self.buttonGroup.addButton(self.stu_cb)
        self.gridLayout_2.addWidget(self.stu_cb, 1, 4, 1, 1)
        self.start_date_de = QtWidgets.QDateEdit(self.query_pane_top)
        self.start_date_de.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 2), QtCore.QTime(0, 0, 0)))
        self.start_date_de.setCalendarPopup(True)
        self.start_date_de.setObjectName("start_date_de")
        self.gridLayout_2.addWidget(self.start_date_de, 1, 1, 1, 1)
        self.from_station_cb = QtWidgets.QComboBox(self.query_pane_top)
        self.from_station_cb.setEditable(True)
        self.from_station_cb.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.from_station_cb.setObjectName("from_station_cb")
        self.from_station_cb.addItem("")
        self.gridLayout_2.addWidget(self.from_station_cb, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.query_pane_top)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.label = QtWidgets.QLabel(self.query_pane_top)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_5 = QtWidgets.QLabel(self.query_pane_top)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.query_pane_top)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.gridLayout_2.addWidget(self.comboBox, 2, 1, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.query_pane_top)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_2, 2, 2, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.query_pane_top)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_3, 2, 3, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.query_pane_top)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_4, 2, 4, 1, 1)
        self.comboBox_5 = QtWidgets.QComboBox(self.query_pane_top)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_5, 2, 5, 1, 1)
        self.gridLayout.addWidget(self.query_pane_top, 0, 0, 1, 1)
        self.widget_4 = QtWidgets.QWidget(Form)
        self.widget_4.setStyleSheet("")
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tickets_tv = QtWidgets.QTableView(self.widget_4)
        self.tickets_tv.setObjectName("tickets_tv")
        self.horizontalLayout.addWidget(self.tickets_tv)
        self.gridLayout.addWidget(self.widget_4, 1, 0, 1, 1)
        self.gridLayout.setRowStretch(0, 2)
        self.gridLayout.setRowStretch(1, 5)

        self.retranslateUi(Form)
        self.pushButton.clicked.connect(Form.query_tickets)
        self.pushButton_2.clicked.connect(Form.book_tickets)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.to_station_cb.setItemText(0, _translate("Form", "广州"))
        self.label_4.setText(_translate("Form", "类型"))
        self.pushButton.setText(_translate("Form", "查询"))
        self.label_3.setText(_translate("Form", "出发日"))
        self.normal_cb.setText(_translate("Form", "普通"))
        self.normal_cb.setProperty("q_value", _translate("Form", "ADULT"))
        self.pushButton_2.setText(_translate("Form", "抢票"))
        self.stu_cb.setText(_translate("Form", "学生"))
        self.stu_cb.setProperty("q_value", _translate("Form", "0X00"))
        self.start_date_de.setDisplayFormat(_translate("Form", "yyyy-MM-dd"))
        self.from_station_cb.setItemText(0, _translate("Form", "武汉"))
        self.label_2.setText(_translate("Form", "到达地"))
        self.label.setText(_translate("Form", "出发地"))
        self.label_5.setText(_translate("Form", "选择车次"))
        self.comboBox.setItemText(0, _translate("Form", "请选车次"))
        self.comboBox_2.setItemText(0, _translate("Form", "请选车次"))
        self.comboBox_3.setItemText(0, _translate("Form", "请选车次"))
        self.comboBox_4.setItemText(0, _translate("Form", "请选车次"))
        self.comboBox_5.setItemText(0, _translate("Form", "请选车次"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

